version: '3.7'
services:
  mongo_container:
    image: mongo:latest
    container_name: 'jeoparty-mongo'
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: jeopartyPW
    ports:
      - 27017:27017
    volumes:
      - ./jeoparty_data_container/data/jeopartydb
volumes:
  jeoparty_data_container: